### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by jshwi** [rkoopmans/python-certificate-chain-resolver#2]
Hi @rkoopmans,

Thanks for this package, I think it's well written

Just wondering if you would like this to be shared and redistributed as an imported component for other packages

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

This would be useful for other packages implementing openssl if you choose to add a license

Cheers,
Stephen

**Comment by rkoopmans** [comment]
hey Stephen, 

Sorry for my late reply, and thank you for your comment.

I'll make a commit and release to include a permissive license (very) soon, I definitely want others to be able to use it :smile:.

**Comment by jshwi** [comment]
Awesome! It'll be good to be able to integrate this in python scripts, the only other alternative I know of is written in go, so this would be very useful for a lot of people I think

**Comment by rkoopmans** [comment]
I released a new version (1.1.1) it has the MIT license included in the Pypi package. It is also tested on python 3.12. I'll go ahead and close this issue.

Thanks for reporting!
