### ISSUE TITLE
Unable to extract root certificate

### ISSUE THREAD

**Issue by y1174804262** [rkoopmans/python-certificate-chain-resolver#6]
Hello, thank you very much for your tool. It has been very helpful to me, but I can only extract intermediate certificates using this tool and cannot further extract root certificates. I would like to ask you what is the reason for this. The results I extracted are shown below, and we can clearly see that the Subject and Issuer values of the last certificate extracted are not the same.
![image](https://github.com/user-attachments/assets/d0cac7bd-1ea5-474f-a371-b2d78c12e8e7)

**Comment by rkoopmans** [comment]
Thanks for your feedback. I chose to not include the root certificates, as they are often not needed and not all certificate issuers include the root certificate in the metadata, so this never worked for all certificates.

I do however understand the need for having this feature, and I had some work in progress to support this usecase, I'll see if I can get that ready to be merged into main

**Comment by rkoopmans** [comment]
I got it to work in another branch (https://github.com/rkoopmans/python-certificate-chain-resolver/tree/dev/1.2) 

Use it like this:

cert_chain_resolver --include-root --use-store-certifi certificate.crt > bundle.crt

I'll make a pypi release soon

**Comment by y1174804262** [comment]
That's cool!!! This is really helpful to me, and I look forward to you publishing the project to pypi. As my native language is not English, it may not be very polite, but I really, really appreciate your help!!!

**Comment by rkoopmans** [comment]
No problem, thank you for giving feedback! The new version is now on pypi:

https://pypi.org/project/cert-chain-resolver/1.3.0/

See the documentation here:

https://certificate-resolver.readthedocs.io/en/latest/api.html#using-the-system-ca-store-or-own-bundle-for-resolving-root-certs

and

https://certificate-resolver.readthedocs.io/en/latest/cli_usage.html#options

**Comment by y1174804262** [comment]
cool! thank you very much!
